version: "3"

tasks:
  default: # If no command is given, default one will run
    cmds:
      - task: generate
  generate:  ## Command to generate
    aliases: ## Aliases of commands
      - gen
    desc: "Generate code from proto files (protobuf + grpc gateway + Swagger + protovalidate)"
    cmds:  ## Commands in terminal
      - buf generate
  lint:
    desc: "Lint the .proto code in proto/ folder by buf"
    cmds:
      - buf lint
  proto:
    desc: "Generating the proto code and create the third_party proto code as well"
    cmds:
      - buf generate
      - buf export buf.build/googleapis/googleapis -o third_party/googleapis
      - buf export buf.build/grpc-ecosystem/grpc-gateway -o third_party/grpc-gateway
      - buf export buf.build/bufbuild/protovalidate -o third_party/protovalidate
#  need to tweak this
#  breaking:
#    desc:
#    cmds: