# ./Taskfile.yaml
# See: https://taskfile.dev/api/

version: "3"

tasks:
  default: # If no command is given, default one will run
    cmds:
      - task: generate
  generate:  ## Command to generate
    aliases: ## Aliases of commands
      - gen
    desc: "Generate code from proto files (protobuf + grpc gateway + Swagger)"
    cmds:  ## Commands in terminal
#      - protoc -I proto -I googleapis proto/**/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - |
        protoc -I proto \
               -I third_party/googleapis \
               -I third_party/grpc-gateway \
               proto/**/*.proto \
               --go_out=./gen/go/ \
               --go_opt=paths=source_relative \
               --go-grpc_out=./gen/go/ \
               --go-grpc_opt=paths=source_relative \
               --grpc-gateway_out=./gen/go/ \
               --grpc-gateway_opt=paths=source_relative \
               --grpc-gateway_opt=logtostderr=true \
               --openapiv2_out=./gen/swagger \
               --openapiv2_opt=logtostderr=true